-- src/main/resources/db/migration/V1__initial_schema.sql
-- USERS TABLE (matches User entity)
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(100) NOT NULL,
                                     phone_number VARCHAR(50) NOT NULL,
                                     email VARCHAR(100),
                                     password VARCHAR(255) NOT NULL,
                                     role VARCHAR(50) NOT NULL DEFAULT 'USER',
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     CONSTRAINT uk_users_username UNIQUE (username),
                                     CONSTRAINT uk_users_phone UNIQUE (phone_number)
);

-- PRODUCTS TABLE (matches Product entity)
CREATE TABLE IF NOT EXISTS products (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(100) NOT NULL,
                                        sku VARCHAR(50) NOT NULL,
                                        price DOUBLE PRECISION NOT NULL CHECK (price >= 0),
                                        stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
                                        description VARCHAR(500),
                                        image_url VARCHAR(255),
                                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT uk_products_sku UNIQUE (sku)
);

CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);

-- SALES TABLE
CREATE TABLE IF NOT EXISTS sales (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE SET NULL,
                                     sale_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     total_amount DOUBLE PRECISION NOT NULL CHECK (total_amount >= 0),
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- SALE ITEMS
CREATE TABLE IF NOT EXISTS sale_items (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
                                          product_id BIGINT NOT NULL REFERENCES products(id),
                                          quantity INTEGER NOT NULL CHECK (quantity > 0),
                                          unit_price DOUBLE PRECISION NOT NULL CHECK (unit_price >= 0),
                                          total_price DOUBLE PRECISION NOT NULL CHECK (total_price >= 0),
                                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sale_items_product ON sale_items(product_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);