-- V8__add_last_updated.sql
ALTER TABLE products
    ADD COLUMN IF NOT EXISTS last_updated BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000;

ALTER TABLE sales
    ADD COLUMN IF NOT EXISTS last_updated BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000;